# Generated by Django 4.0.1 on 2022-02-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='convert',
            field=models.JSONField(),
        ),
    ]
