# Generated by Django 4.0.1 on 2022-02-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_input_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='data',
        ),
    ]
